import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Arks of Omen - Campaign Guide</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.parallaxContainer}>
        <div className={styles.titleContainer}>
          <h2 className={styles.arksTitle}>ARKS OF OMEN</h2>
          <h1 className={styles.arksSubtitle}>CAMPAIGN GUIDE</h1>
        </div>
        {/* <p>
          Cerro Torre is a mountain of sheer beauty whose spectacular attributes
          make it an unique gem in Argentina.
        </p> */}
      </section>

      <section className={styles.buffer}>
        <div className={styles.contentContainer}>
          <div className={styles.contentColumn}>
            <h2 className={styles.contentTitle}>INTRODUCTION</h2>
            <div className={styles.contentText}>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Atque
              quisquam sapiente ad itaque, tempore exercitationem facilis
              aliquam et perferendis quia omnis animi nemo inventore ducimus
              numquam placeat sit facere eaque. Lorem ipsum dolor sit amet
              consectetur adipisicing elit. Delectus, ullam cupiditate soluta
              vitae blanditiis animi fugit ratione rerum quae nulla, alias
              beatae autem porro, error distinctio aliquid fugiat accusamus
              repellat. Lorem ipsum dolor, sit amet consectetur adipisicing
              elit. Ad omnis optio reprehenderit assumenda, enim cupiditate
              ipsum dignissimos distinctio ex ut tempore obcaecati aspernatur
              hic ratione, cumque voluptate deleniti, quo labore!
            </div>
          </div>
          <div className={styles.contentColumn}>
            <h2 className={styles.contentTitle}>COLUMN 2</h2>
            <div className={styles.contentText}>
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Ratione
              in nam ab officia adipisci dolores, tenetur esse numquam?
              Aspernatur autem laborum accusantium debitis consequatur excepturi
              reiciendis quidem ratione voluptas dolore?
            </div>
          </div>
        </div>
      </section>

      <section
        className={`${styles.parallaxContainer} ${styles.parallaxContainer2}`}
      >
        <div className={styles.card}>
          <div className={styles.cardImg}></div>
          <h3>Hiking</h3>
          <p>
            Explore the myriad of trails through the mountaineous. Choose the
            difficulty appropriate to your fitness level.
          </p>
          <a href="#">Learn more</a>
        </div>
        <div className={styles.card}>
          <div className={styles.cardImg}></div>
          <h3>Rock climbing</h3>
          <p>
            The goal is to reach the summit of a formation or the endpoint of a
            usually pre-defined route without falling
          </p>
          <a href="#">Learn more</a>
        </div>
        <div className={styles.card}>
          <div className={styles.cardImg}></div>
          <h3>Caving</h3>
          <p>
            Exploring underground through networks of tunnels and passageways,
            which can be natural or artificial.
          </p>
          <a href="#">Learn more</a>
        </div>
        <div className={styles.card}>
          <div className={styles.cardImg}></div>
          <h3>Paragliding</h3>
          <p>
            Get lift off from the mountain and enjoy through the splendor of the
            surrounding landscape by parachute.
          </p>
          <a href="#">Learn more</a>
        </div>
      </section>

      <section className={styles.buffer}></section>
      {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      {/* </section> */}
    </>
  );
}
